name: CoderyoGUI
version: 1.0
main: com.example.coderyogui.CoderyoGUI
api-version: 1.13
commands:
  coderyogui:
    description: Main command for CoderyoGUI
    usage: /<command> [open|edit|del] [args]
permissions:
  coderyogui.use:
    description: Allows using /coderyogui command
    default: true
  coderyogui.create:
    description: Allows creating new GUIs
    default: op
  coderyogui.edit.*:
    description: Allows editing all GUIs
    default: op
  coderyogui.del:
    description: Allows deleting GUIs
    default: op