name: CoderyoGUI
version: 1.0
main: com.example.coderyogui.CoderyoGUI
api-version: 1.21
commands:
  coderyogui:
    description: 主命令用於管理 CoderyoGUI
    usage: /<command> [open|edit|del] [GUI名]
    aliases: [cgui]
permissions:
  coderyogui.use:
    description: 允許使用 /coderyogui 命令打開主菜單或 GUI
    default: op
  coderyogui.create:
    description: 允許創建新 GUI
    default: op
  coderyogui.edit.*:
    description: 允許編輯所有 GUI
    default: op
  coderyogui.del:
    description: 允許刪除 GUI
    default: op